name: swgs-abscn
channels:
  - conda-forge
  - bioconda 
dependencies:
  - r-base=4.3.3
  - snakemake=5.10
  - python=3.10
  - pandas
  - setuptools=81.0
  - ruamel.yaml
  - samtools
  - bioconductor-biobase
  - bioconductor-biocgenerics
  - r-tidyverse
  - r-matrixstats
  - r-plyr
  - r-domc
  - r-foreach
  - bioconductor-qdnaseq
  - bioconductor-qdnaseq.hg19
  - r-remotes
